### ISSUE TITLE
Is this Production Ready?

### ISSUE THREAD

**Issue by usopan** [count0ru/k8s-clickhouse-v2#1]
Hi, 
Just wanted to understand if this repo can be used to deploy clickhouse in production environments?
I can contribute the changes if you tell me the recommended deployment.

One thing I can see missing is Persistent Volumes. Is this deployment not intented to persist data?

**Comment by derekperkins** [comment]
I'm also very interested in this.

**Comment by count0ru** [comment]
No, this is not for production environments. You need to add any persistent volume type that will fit you.
